set/get_user_sshkeys: Add negative tests
Add two negative test scenarios for set/get_user_sshkeys:
1) acl_test:
Set libvirt API access dirver to polkit, but don't configure
polkit rules for set/get_user_sshkeys. When set/get_user_sshkeys
is called, such error will be reported:
error: access denied

2) no_start_qemu_guest_agent
Stop qemu guest agent in guest, then set/get_user_sshkeys is
called, such error will be reported:
QEMU guest agent is not connected

Signed-off-by: Fangge Jin <fjin@redhat.com>